import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * ~33 szobanövény, gazdag attribútumokkal.
 * A pet_safe (háziállat-barát) értékek szándékosan valósághűek (ASPCA-alapon),
 * hogy a "melyik biztonságos macskára?" típusú kérdésekre helyes választ adjunk.
 *
 * Kötött szókészletek:
 *  - size_category: kicsi | közepes | nagy
 *  - light_need:    alacsony | közepes | erős
 *  - water_frequency: ritka | heti | gyakori
 *  - care_level:    könnyű | közepes | nehéz
 *  - category:      Levéldísznövény | Pálma | Páfrány | Pozsgás | Kaktusz | Virágzó | Függő növény
 */
const plants = [
  // --- Levéldísznövények ---
  {
    name: 'Monstera',
    scientificName: 'Monstera deliciosa',
    category: 'Levéldísznövény',
    price: 12900,
    sizeCategory: 'nagy',
    heightCm: 120,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld',
    inStock: 8,
    description: 'Látványos, hasított levelű trópusi levéldísznövény.',
  },
  {
    name: 'Anyósnyelv',
    scientificName: 'Dracaena trifasciata',
    category: 'Levéldísznövény',
    price: 4900,
    sizeCategory: 'közepes',
    heightCm: 70,
    lightNeed: 'alacsony',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld-csíkos',
    inStock: 20,
    description: 'Szinte elpusztíthatatlan, ritkán öntözendő, árnyéktűrő növény.',
  },
  {
    name: 'ZZ növény',
    scientificName: 'Zamioculcas zamiifolia',
    category: 'Levéldísznövény',
    price: 6900,
    sizeCategory: 'közepes',
    heightCm: 60,
    lightNeed: 'alacsony',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'sötétzöld',
    inStock: 15,
    description: 'Fényes levelű, vízraktározó, nagyon igénytelen szobanövény.',
  },
  {
    name: 'Gumifa',
    scientificName: 'Ficus elastica',
    category: 'Levéldísznövény',
    price: 8500,
    sizeCategory: 'nagy',
    heightCm: 130,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: false,
    color: 'sötétzöld',
    inStock: 10,
    description: 'Bőrszerű, fényes levelű, dekoratív szobafa.',
  },
  {
    name: 'Hegedűfikusz',
    scientificName: 'Ficus lyrata',
    category: 'Levéldísznövény',
    price: 15900,
    sizeCategory: 'nagy',
    heightCm: 150,
    lightNeed: 'erős',
    waterFrequency: 'heti',
    careLevel: 'nehéz',
    petSafe: false,
    color: 'zöld',
    inStock: 6,
    description: 'Nagy, hegedű formájú levelekkel; sok fényt és odafigyelést kíván.',
  },
  {
    name: 'Sárkányfa',
    scientificName: 'Dracaena marginata',
    category: 'Levéldísznövény',
    price: 7200,
    sizeCategory: 'nagy',
    heightCm: 120,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld-piros szegély',
    inStock: 12,
    description: 'Karcsú törzsű, keskeny, piros szegélyű levelű dísznövény.',
  },
  {
    name: 'Kroton',
    scientificName: 'Codiaeum variegatum',
    category: 'Levéldísznövény',
    price: 5600,
    sizeCategory: 'közepes',
    heightCm: 55,
    lightNeed: 'erős',
    waterFrequency: 'heti',
    careLevel: 'nehéz',
    petSafe: false,
    color: 'tarka piros-sárga',
    inStock: 9,
    description: 'Élénk, tarka lombú növény; erős fényt igényel a színekhez.',
  },
  {
    name: 'Csörgőkígyó-kalatea',
    scientificName: 'Calathea lancifolia',
    category: 'Levéldísznövény',
    price: 4800,
    sizeCategory: 'közepes',
    heightCm: 50,
    lightNeed: 'közepes',
    waterFrequency: 'gyakori',
    careLevel: 'nehéz',
    petSafe: true,
    color: 'zöld-mintás',
    inStock: 12,
    description: 'Mintás, hullámos levelű, páraigényes, háziállat-barát növény.',
  },
  {
    name: 'Pávalevél',
    scientificName: 'Calathea orbifolia',
    category: 'Levéldísznövény',
    price: 6200,
    sizeCategory: 'közepes',
    heightCm: 45,
    lightNeed: 'közepes',
    waterFrequency: 'gyakori',
    careLevel: 'nehéz',
    petSafe: true,
    color: 'ezüstzöld csíkos',
    inStock: 10,
    description: 'Nagy, kerek, ezüstös csíkozású levelekkel; macska- és kutyabarát.',
  },
  {
    name: 'Törpe bors',
    scientificName: 'Peperomia obtusifolia',
    category: 'Levéldísznövény',
    price: 2800,
    sizeCategory: 'kicsi',
    heightCm: 25,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld',
    inStock: 24,
    description: 'Húsos levelű, kompakt, kezdőbarát és pet-safe növény.',
  },
  {
    name: 'Kínai pénzfa',
    scientificName: 'Pilea peperomioides',
    category: 'Levéldísznövény',
    price: 3600,
    sizeCategory: 'kicsi',
    heightCm: 25,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld',
    inStock: 21,
    description: 'Kerek, érme alakú levelekkel; könnyen szaporítható, macskabarát.',
  },
  {
    name: 'Vaslevél',
    scientificName: 'Aspidistra elatior',
    category: 'Levéldísznövény',
    price: 6800,
    sizeCategory: 'közepes',
    heightCm: 60,
    lightNeed: 'alacsony',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'sötétzöld',
    inStock: 12,
    description: 'Rendkívül tűrőképes, sötét sarokba is jó, háziállat-barát növény.',
  },
  {
    name: 'Guyanai pénzfa',
    scientificName: 'Pachira aquatica',
    category: 'Levéldísznövény',
    price: 8900,
    sizeCategory: 'nagy',
    heightCm: 120,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld',
    inStock: 9,
    description: 'Fonott törzsű, "szerencsehozó", macska- és kutyabarát szobafa.',
  },

  // --- Függő növények ---
  {
    name: 'Aranyrepkény',
    scientificName: 'Epipremnum aureum',
    category: 'Függő növény',
    price: 3500,
    sizeCategory: 'közepes',
    heightCm: 40,
    lightNeed: 'alacsony',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld-sárga tarka',
    inStock: 25,
    description: 'Igénytelen, gyorsan növő, csüngő vagy kúszó növény.',
  },
  {
    name: 'Szívlevelű filodendron',
    scientificName: 'Philodendron hederaceum',
    category: 'Függő növény',
    price: 4200,
    sizeCategory: 'közepes',
    heightCm: 45,
    lightNeed: 'alacsony',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld',
    inStock: 18,
    description: 'Alacsony fényt is jól tűrő, hálás kúszónövény.',
  },
  {
    name: 'Imádkozó növény',
    scientificName: 'Maranta leuconeura',
    category: 'Függő növény',
    price: 3900,
    sizeCategory: 'kicsi',
    heightCm: 25,
    lightNeed: 'közepes',
    waterFrequency: 'gyakori',
    careLevel: 'közepes',
    petSafe: true,
    color: 'zöld-piros erezet',
    inStock: 17,
    description: 'Este összecsukja leveleit; dekoratív erezet, háziállat-barát.',
  },
  {
    name: 'Viaszvirág',
    scientificName: 'Hoya carnosa',
    category: 'Függő növény',
    price: 4700,
    sizeCategory: 'közepes',
    heightCm: 40,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld, viaszos',
    inStock: 14,
    description: 'Illatos, viaszos virágokkal; ritkán öntözendő, pet-safe.',
  },

  // --- Pálmák ---
  {
    name: 'Aranypálma',
    scientificName: 'Dypsis lutescens',
    category: 'Pálma',
    price: 9900,
    sizeCategory: 'nagy',
    heightCm: 140,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: true,
    color: 'zöld',
    inStock: 11,
    description: 'Levegőt tisztító, tömött lombú, háziállat-barát pálma.',
  },
  {
    name: 'Hegyipálma',
    scientificName: 'Chamaedorea elegans',
    category: 'Pálma',
    price: 4500,
    sizeCategory: 'közepes',
    heightCm: 60,
    lightNeed: 'alacsony',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld',
    inStock: 16,
    description: 'Kompakt, árnyéktűrő, kezdőbarát és pet-safe pálma.',
  },
  {
    name: 'Kentia pálma',
    scientificName: 'Howea forsteriana',
    category: 'Pálma',
    price: 18900,
    sizeCategory: 'nagy',
    heightCm: 160,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: true,
    color: 'zöld',
    inStock: 5,
    description: 'Elegáns, robusztus, tekintélyes méretű szobapálma.',
  },
  {
    name: 'Elefántlábfa',
    scientificName: 'Beaucarnea recurvata',
    category: 'Pálma',
    price: 7900,
    sizeCategory: 'közepes',
    heightCm: 80,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld',
    inStock: 13,
    description: 'Vízraktározó törzs, ritka öntözés; háziállat-barát.',
  },

  // --- Páfrányok ---
  {
    name: 'Kardpáfrány',
    scientificName: 'Nephrolepis exaltata',
    category: 'Páfrány',
    price: 3400,
    sizeCategory: 'közepes',
    heightCm: 45,
    lightNeed: 'közepes',
    waterFrequency: 'gyakori',
    careLevel: 'közepes',
    petSafe: true,
    color: 'élénkzöld',
    inStock: 19,
    description: 'Buja, csüngő páfrány; magas páratartalmat kedvel, pet-safe.',
  },
  {
    name: 'Fészekpáfrány',
    scientificName: 'Asplenium nidus',
    category: 'Páfrány',
    price: 4100,
    sizeCategory: 'közepes',
    heightCm: 50,
    lightNeed: 'alacsony',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'világoszöld',
    inStock: 15,
    description: 'Tölcséres levélrózsa; árnyéktűrő és háziállat-barát.',
  },

  // --- Pozsgások ---
  {
    name: 'Aloe vera',
    scientificName: 'Aloe vera',
    category: 'Pozsgás',
    price: 2900,
    sizeCategory: 'kicsi',
    heightCm: 30,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöldesszürke',
    inStock: 30,
    description: 'Húsos, gyógyhatású levelű pozsgás; sok napfényt kíván.',
  },
  {
    name: 'Pénzfa',
    scientificName: 'Crassula ovata',
    category: 'Pozsgás',
    price: 3200,
    sizeCategory: 'kicsi',
    heightCm: 35,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld',
    inStock: 20,
    description: 'Vastag, fényes levelű, fás szárú pozsgás.',
  },
  {
    name: 'Zebrakaktusz',
    scientificName: 'Haworthiopsis fasciata',
    category: 'Pozsgás',
    price: 2400,
    sizeCategory: 'kicsi',
    heightCm: 15,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'zöld-fehér csíkos',
    inStock: 26,
    description: 'Apró, fehér csíkos pozsgás; asztali méret, macskabarát.',
  },

  // --- Kaktuszok ---
  {
    name: 'Karácsonyi kaktusz',
    scientificName: 'Schlumbergera bridgesii',
    category: 'Kaktusz',
    price: 3300,
    sizeCategory: 'kicsi',
    heightCm: 25,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'könnyű',
    petSafe: true,
    color: 'rózsaszín virág',
    inStock: 18,
    description: 'Télen virágzó, tüske nélküli, háziállat-barát kaktusz.',
  },
  {
    name: 'Aranylabda kaktusz',
    scientificName: 'Echinocactus grusonii',
    category: 'Kaktusz',
    price: 3900,
    sizeCategory: 'kicsi',
    heightCm: 20,
    lightNeed: 'erős',
    waterFrequency: 'ritka',
    careLevel: 'könnyű',
    petSafe: false,
    color: 'zöld, tüskés',
    inStock: 15,
    description: 'Gömb alakú, sárga tüskés kaktusz; sok napfényt igényel.',
  },

  // --- Virágzók ---
  {
    name: 'Vitorlavirág',
    scientificName: 'Spathiphyllum wallisii',
    category: 'Virágzó',
    price: 3900,
    sizeCategory: 'közepes',
    heightCm: 45,
    lightNeed: 'alacsony',
    waterFrequency: 'gyakori',
    careLevel: 'közepes',
    petSafe: false,
    color: 'fehér virág',
    inStock: 22,
    description: 'Fehér, vitorla alakú virágokkal; árnyékkedvelő.',
  },
  {
    name: 'Flamingóvirág',
    scientificName: 'Anthurium andraeanum',
    category: 'Virágzó',
    price: 5900,
    sizeCategory: 'közepes',
    heightCm: 40,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: false,
    color: 'piros',
    inStock: 14,
    description: 'Viaszos, piros virágokkal; egész évben dekoratív.',
  },
  {
    name: 'Lepkeorchidea',
    scientificName: 'Phalaenopsis',
    category: 'Virágzó',
    price: 4900,
    sizeCategory: 'kicsi',
    heightCm: 40,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: true,
    color: 'fehér-lila',
    inStock: 20,
    description: 'Hosszan virágzó, elegáns, háziállat-barát orchidea.',
  },
  {
    name: 'Afrikai ibolya',
    scientificName: 'Saintpaulia ionantha',
    category: 'Virágzó',
    price: 2200,
    sizeCategory: 'kicsi',
    heightCm: 15,
    lightNeed: 'közepes',
    waterFrequency: 'heti',
    careLevel: 'közepes',
    petSafe: true,
    color: 'lila',
    inStock: 27,
    description: 'Kompakt, gyakran virágzó, ablakpárkányra ideális, pet-safe.',
  },
];

async function main() {
  console.log(`🌱 Seed indul: ${plants.length} növény...`);
  await prisma.product.deleteMany();
  await prisma.product.createMany({ data: plants });
  const count = await prisma.product.count();
  console.log(`✅ Kész. ${count} növény az adatbázisban.`);
}

main()
  .catch((e) => {
    console.error('❌ Seed hiba:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
